function guardarDeteccionesImagenes(datos, outputDir, doShow)
    % Esta función recibe el struct datos y la carpeta destino
    % Genera automáticamente process_start.png y process_end.png

    fases = {'start', 'end'};
    for k = 1:numel(fases)
        f = fases{k};
        outputPath = fullfile(outputDir, ['process_' f '.png']);
        visualizarDetecciones( ...
            datos.(f).img, ...
            datos.(f).det, ...
            datos.(f).cmX, ...
            datos.(f).cmY, ...
            outputPath, ...
            doShow ...
        );
    end
end
