% Crear figura principal
fig = uifigure("Position", [100 100 1366 757], ...
               "Color", [0.1 0.1 0.1]);  % Fondo oscuro

bgHex = "#1a1a1a";              % Fondo HTML
btnSize = [185.3, 59.7];        % Tamaño fijo de botón

% START VIDEO
round_button(fig, ...
    "Position", [421, 757-572.3-btnSize(2), btnSize], ...
    "Color", "#0097a7", ...
    "HoverColor", "#00ffff", ...
    "FontColor", "white", ...
    "Bold", true, ...
    "Text", "Start Video", ...
    "BackgroundHexColor", bgHex, ...
    "ButtonPushedFcn", @(src, event) disp("Start Video"));

% CAPTURE 1
round_button(fig, ...
    "Position", [421, 757-504.3-btnSize(2), btnSize], ...
    "Color", "#81d4fa", ...
    "HoverColor", "#ffffff", ...
    "FontColor", "black", ...
    "Text", "Capture 1", ...
    "BackgroundHexColor", bgHex, ...
    "ButtonPushedFcn", @(src, event) disp("Capture 1"));

% CAPTURE 2
round_button(fig, ...
    "Position", [421, 757-431.8-btnSize(2), btnSize], ...
    "Color", "#81d4fa", ...
    "HoverColor", "#ffffff", ...
    "FontColor", "black", ...
    "Text", "Capture 2", ...
    "BackgroundHexColor", bgHex, ...
    "ButtonPushedFcn", @(src, event) disp("Capture 2"));

% LOAD 1
round_button(fig, ...
    "Position", [90, 757-321.9-btnSize(2), btnSize], ...
    "Color", "#4dd0e1", ...
    "HoverColor", "#b2ebf2", ...
    "FontColor", "black", ...
    "Text", "Load 1", ...
    "BackgroundHexColor", bgHex, ...
    "ButtonPushedFcn", @(src, event) disp("Load 1"));

% LOAD 2
round_button(fig, ...
    "Position", [421, 757-321.9-btnSize(2), btnSize], ...
    "Color", "#4dd0e1", ...
    "HoverColor", "#b2ebf2", ...
    "FontColor", "black", ...
    "Text", "Load 2", ...
    "BackgroundHexColor", bgHex, ...
    "ButtonPushedFcn", @(src, event) disp("Load 2"));

% SAVE 1
round_button(fig, ...
    "Position", [46, 757-10.3-btnSize(2), btnSize], ...
    "Color", "#00e4ff", ...
    "HoverColor", "#80ffff", ...
    "FontColor", "black", ...
    "Text", "Save 1", ...
    "BackgroundHexColor", bgHex, ...
    "ButtonPushedFcn", @(src, event) disp("Save 1"));

% CLEAR ALL
round_button(fig, ...
    "Position", [243, 757-10.3-btnSize(2), btnSize], ...
    "Color", "#00e4ff", ...
    "HoverColor", "#80ffff", ...
    "FontColor", "black", ...
    "Text", "Clear all", ...
    "BackgroundHexColor", bgHex, ...
    "ButtonPushedFcn", @(src, event) disp("Clear all"));

% SAVE 2
round_button(fig, ...
    "Position", [441, 757-10.3-btnSize(2), btnSize], ...
    "Color", "#00e4ff", ...
    "HoverColor", "#80ffff", ...
    "FontColor", "black", ...
    "Text", "Save 2", ...
    "BackgroundHexColor", "#d6e7e1", ...
    "ButtonPushedFcn", @(src, event) disp("Save 2"));

% PROCESS
round_button(fig, ...
    "Position", [929, 757-596.3-btnSize(2), btnSize], ...
    "Color", "#ff0a0a", ...
    "HoverColor", "#ff6666", ...
    "FontColor", "white", ...
    "Bold", true, ...
    "Text", "Process", ...
    "BackgroundHexColor", bgHex, ...
    "ButtonPushedFcn", @(src, event) disp("Process"));

